import { NextResponse } from "next/server";
import JSZip from "jszip";
import { ZodError } from "zod";

import { loadCasePackageFromFiles } from "../../../../lib/case-package/loader";

function normalizeZipPath(path: string): string {
  const parts = path.split("/").filter(Boolean);
  const topLevel = new Set([
    "manifest.json",
    "case.json",
    "story",
    "agents",
    "facts",
    "acts",
    "scenes",
    "clues",
    "relationships",
    "propagation",
    "contradictions",
    "truth",
    "victims",
    "accusation"
  ]);
  if (parts.length > 1 && !topLevel.has(parts[0])) {
    return parts.slice(1).join("/");
  }
  return parts.join("/");
}

export async function POST(request: Request) {
  const formData = await request.formData().catch(() => undefined);
  const file = formData?.get("file");

  if (
    !file ||
    typeof file !== "object" ||
    typeof (file as { arrayBuffer?: unknown }).arrayBuffer !== "function"
  ) {
    return NextResponse.json(
      {
        ok: false,
        issues: [
          {
            severity: "fatal",
            code: "missing-file",
            filePath: "upload",
            message: "Upload a case package zip file.",
            suggestion: "Choose a .zip file generated by new-novels-case-adapter."
          }
        ]
      },
      { status: 400 }
    );
  }

  try {
    const zip = await JSZip.loadAsync(await (file as File).arrayBuffer());
    const files = new Map<string, string>();

    await Promise.all(
      Object.values(zip.files)
        .filter((entry) => !entry.dir)
        .map(async (entry) => {
          files.set(normalizeZipPath(entry.name), await entry.async("string"));
        })
    );

    const loaded = loadCasePackageFromFiles(files);

    return NextResponse.json({
      ok: true,
      manifest: loaded.manifest,
      caseSummary: {
        id: loaded.caseFile.id,
        title: loaded.caseFile.title,
        chapters: loaded.caseFile.chapters.length,
        agents: loaded.caseFile.agents.length,
        acts: loaded.caseFile.acts.length,
        clues: loaded.caseFile.clues.length,
        accusationQuestions: loaded.caseFile.accusation.questions.length
      },
      issues: []
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown package error.";
    const issues =
      error instanceof ZodError
        ? error.issues.map((issue) => ({
            severity: "fatal",
            code: issue.code,
            filePath: "case.json",
            fieldPath: issue.path.join("."),
            message: issue.message,
            suggestion: "Update the package data so it satisfies case-package/v1."
          }))
        : [
            {
              severity: "fatal",
              code: "invalid-package",
              filePath: "upload.zip",
              message,
              suggestion: "Check that the zip contains a complete case-package/v1 layout."
            }
          ];

    return NextResponse.json({ ok: false, issues }, { status: 400 });
  }
}
